### 1. Register a new user
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Pascal",
  "email": "pascal@test.com",
  "password": "password123"
}

### 2. Login to get a token
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "pascal@test.com",
  "password": "password123"
}

### 3. Create an Expense (Requires Token)
# Paste the token you got from Login after 'Bearer'
POST http://localhost:5000/api/expenses
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NDgzOGFhZTc0OWQ3MjlmYWZhZDkzZiIsImlhdCI6MTc2OTMwNzY0OSwiZXhwIjoxNzcxODk5NjQ5fQ.pXd33DkOC8KD95Z3jWisaCcsR9QAmasf24gi48G32Ug

{
  "text": "Bag of Takis",
  "amount": 3,
  "category": "Food"
}

### 4. Get all my expenses
GET http://localhost:5000/api/expenses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5NDgzOGFhZTc0OWQ3MjlmYWZhZDkzZiIsImlhdCI6MTc2OTMwNzY0OSwiZXhwIjoxNzcxODk5NjQ5fQ.pXd33DkOC8KD95Z3jWisaCcsR9QAmasf24gi48G32Ug